[project]
name = "dewahwah"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Ahmad Hassan", email = "ahmad.tanveer@ccript.com" }
]
requires-python = ">=3.11"
dependencies = [
    "audio-separator>=0.47.0",
    "demucs>=4.0.1",
    "librosa>=0.11.0",
    "numpy>=2.4.6",
    "pyannote-audio>=4.0.7",
    "soundfile>=0.14.0",
    "speechbrain>=1.1.1",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
]

[project.scripts]
dewahwah = "dewahwah:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
